fail_fast: false
exclude: |
  (^alembic/)|
  (\.ruff_cache/)
repos:
  - repo: local
    hooks:
      - id: ruff-format
        name: Ruff Formatter
        entry: ruff format
        language: system
        files: \.py$
        types: [python]
  - repo: local
    hooks:
      - id: ruff-linter
        name: Ruff Linter
        entry: ruff check
        language: system
        files: \.py$
        types: [python]