"""added triggers for plugins

Revision ID: 3efdb66da93e
Revises: ad9494bd8503
Create Date: 2025-10-19 15:32:46.966855

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3efdb66da93e'
down_revision: Union[str, None] = 'ad9494bd8503'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugin_triggers',
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('event_type', postgresql.ENUM('TEXT', 'COMMAND', 'BUTTON', name='triggereventtype', create_type=False), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.plugin_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.add_column('plugins', sa.Column('readme_file_path', sa.String(length=256), nullable=False))
    op.drop_column('plugins', 'description')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('plugins', sa.Column('description', sa.VARCHAR(length=4096), autoincrement=False, nullable=False))
    op.drop_column('plugins', 'readme_file_path')
    op.drop_table('plugin_triggers')
    # ### end Alembic commands ###
