"""added excel block

Revision ID: 7739ec59d86f
Revises: 9591903b1e53
Create Date: 2025-09-08 16:17:00.844850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7739ec59d86f'
down_revision: Union[str, None] = '9591903b1e53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excel_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excel_blocks')
    # ### end Alembic commands ###
