"""init models

Revision ID: 9591903b1e53
Revises: 
Create Date: 2025-08-12 00:06:47.658654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9591903b1e53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plugins',
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('handlers_file_path', sa.String(length=256), nullable=False),
    sa.Column('db_funcs_file_path', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('plugin_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('triggers',
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('TEXT', 'COMMAND', 'BUTTON', name='triggereventtype'), nullable=False),
    sa.Column('value', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('trigger_id')
    )
    op.create_table('users',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('tg_id', sa.BigInteger(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('tg_id')
    )
    op.create_table('projects',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('start_message', sa.String(length=4096), nullable=False),
    sa.Column('start_keyboard_type', sa.Enum('INLINE_KEYBOARD', 'REPLY_KEYBOARD', name='keyboardtype'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('dialogues',
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('trigger_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['trigger_id'], ['triggers.trigger_id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('dialogue_id')
    )
    op.create_table('projects_plugins',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('plugin_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['plugin_id'], ['plugins.plugin_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('project_id', 'plugin_id')
    )
    op.create_table('blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.dialogue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id'),
    sa.UniqueConstraint('dialogue_id', 'sequence_number')
    )
    op.create_table('templates',
    sa.Column('template_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('description', sa.String(length=4096), nullable=False),
    sa.Column('image_path', sa.String(length=512), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('dialogue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dialogue_id'], ['dialogues.dialogue_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('template_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('api_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('http_method', sa.Enum('GET', 'POST', 'PUT', 'DELETE', 'PATCH', 'CONNECT', 'HEAD', 'OPTIONS', name='httpmethod'), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('body', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('csv_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=256), nullable=False),
    sa.Column('data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('email_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=128), nullable=False),
    sa.Column('text', sa.String(length=8192), nullable=False),
    sa.Column('recipient_email', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('image_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('question_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=4096), nullable=False),
    sa.Column('answer_type', sa.Enum('ANY', 'TEXT', 'INT', 'EMAIL', 'PHONE_NUMBER', name='answermessagetype'), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    op.create_table('text_blocks',
    sa.Column('block_id', sa.Integer(), nullable=False),
    sa.Column('message_text', sa.String(length=4096), nullable=False),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.block_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('block_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('text_blocks')
    op.drop_table('question_blocks')
    op.drop_table('image_blocks')
    op.drop_table('email_blocks')
    op.drop_table('csv_blocks')
    op.drop_table('api_blocks')
    op.drop_table('templates')
    op.drop_table('blocks')
    op.drop_table('projects_plugins')
    op.drop_table('dialogues')
    op.drop_table('projects')
    op.drop_table('users')
    op.drop_table('triggers')
    op.drop_table('plugins')

    op.execute('DROP TYPE triggereventtype;')
    op.execute('DROP TYPE httpmethod;')
    op.execute('DROP TYPE answermessagetype;')
    op.execute('DROP TYPE keyboardtype;')
    # ### end Alembic commands ###
