"""added readme to dialogue templates

Revision ID: b643a0de2a79
Revises: 3efdb66da93e
Create Date: 2025-11-04 00:24:47.687781

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b643a0de2a79'
down_revision: Union[str, None] = '3efdb66da93e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('templates', sa.Column('readme_file_path', sa.String(length=256), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('templates', 'readme_file_path')
    # ### end Alembic commands ###
