"""added payments

Revision ID: d2c66c895be5
Revises: 46cd158bcf32
Create Date: 2025-11-12 12:38:06.538016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2c66c895be5'
down_revision: Union[str, None] = '46cd158bcf32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('payment_id', sa.Uuid(), nullable=False),
    sa.Column('yookassa_payment_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'CANCELED', 'WAITING_FOR_CAPTURE', name='paymentstatus'), nullable=False),
    sa.Column('confirmation_url', sa.String(length=2048), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('subscription_id', sa.Uuid(), nullable=True),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payments')
    op.execute('DROP TYPE paymentstatus;')
    # ### end Alembic commands ###
