# Free tariff
MAX_PROJECTS_WITH_FREE_PLAN = 1
MAX_DIALOGUES_WITH_FREE_PLAN = 1

# PRO tariff
MAX_PROJECTS_WITH_PRO_PLAN = 3
MAX_DIALOGUES_WITH_PRO_PLAN = 10

# Common limits
MAX_PLUGINS_PER_PROJECT = 3
